### ISSUE TITLE
Tests break for Chameleon >= 4.5

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.macro#9]
The last test with `4.4.3` was successful: https://github.com/zopefoundation/z3c.macro/actions/runs/7519022757
The next one running with `4.5.1` failed: https://github.com/zopefoundation/z3c.macro/actions/runs/7601065572

```python
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/doctest.py", line 1359, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest README.rst[25]>", line 1, in <module>
        print(view().strip())
      File "<doctest README.rst[17]>", line 6, in __call__
        return self.index(**kwargs)
      File "/home/runner/work/z3c.macro/z3c.macro/.tox/py312/lib/python3.12/site-packages/zope/browserpage/viewpagetemplatefile.py", line 83, in __call__
        return self.__func__(im_self, *args, **kw)
      File "/home/runner/work/z3c.macro/z3c.macro/.tox/py312/lib/python3.12/site-packages/zope/browserpage/viewpagetemplatefile.py", line 47, in __call__
        s = self.pt_render(
      File "/home/runner/work/z3c.macro/z3c.macro/.tox/py312/lib/python3.12/site-packages/zope/pagetemplate/pagetemplate.py", line 130, in pt_render
        raise PTRuntimeError(str(self._v_errors))
       - Warning: Compilation failed
       - Warning: builtins.NameError: name '_MacroGetter' is not defined
    zope.pagetemplate.pagetemplate.PTRuntimeError: ['Compilation failed', "builtins.NameError: name '_MacroGetter' is not defined"]
```

@malthe does this ring a bell for you?

**Comment by malthe** [comment]
@icemac doesn't ring a bell – I'll take a look.

I think what happened is that at the time, I didn't have too much of an awareness of the "public API" of Chameleon and so to make everything work, packages such as z3c.macro and z3c.pt would import liberally from Chameleon and use some of the internal machinery in a way that's not tested in Chameleon proper.

So I have been trying to clean up things a bit in Chameleon, causing a bit of trouble down the road unfortunately.

**Comment by malthe** [comment]
Fixed in https://github.com/malthe/chameleon/releases/tag/4.5.2.

**Comment by icemac** [comment]
@malthe Thank you this was a quick fix!
